spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: 1985
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
